import React, { createContext, useContext, useState, useEffect } from 'react';

// Top 10 Languages
export type Language = 
  | 'pt' // Portuguese (Brazil)
  | 'en' // English (US)
  | 'es' // Spanish
  | 'fr' // French
  | 'de' // German
  | 'it' // Italian
  | 'zh' // Chinese
  | 'ja' // Japanese
  | 'ru' // Russian
  | 'ko'; // Korean

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Base translations for English (used as fallback for new languages)
const enTranslations = {
    // Menu & General
    'general_panel': 'Dashboard',
    'registrations': 'Records',
    'studio_profile': 'Studio Profile',
    'team': 'Team',
    'students': 'My Students',
    'settings': 'Settings',
    'strategy': 'Strategy',
    'planning_ai': 'AI Planning',
    'pilates_rehab': 'Pilates Rehab',
    'content_agent': 'Content Assistant',
    'finance_calc': 'Financial Calc',
    'smart_pricing': 'Smart Pricing',
    'newsletter': 'Newsletter Creator',
    'tracking': 'Tracking',
    'student_evolution': 'Student Evolution',
    'class_ratings': 'Class Ratings',
    'suggestions': 'Suggestions',
    'dark_mode': 'Dark',
    'light_mode': 'Light',
    'logout': 'Logout',
    'admin_panel': 'Admin Panel',
    'owner': 'Owner',
    'instructor': 'Instructor',
    'student': 'Student',
    'save_all': 'Save All',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'loading': 'Loading...',
    'search': 'Search...',
    'actions': 'Actions',
    'active': 'Active',
    'inactive': 'Inactive',
    'new': 'New',
    'view_details': 'View Details',
    'back': 'Back',
    'next': 'Next',
    'history': 'History',
    'clear': 'Clear',

    // Content Agent
    'content_title': 'Content Assistant',
    'content_subtitle': 'Create posts, images, and videos aligned with your brand.',
    'tab_persona': 'My Brand',
    'tab_generator': 'Create',
    'tab_planner': 'Planner',
    'persona_title': 'Studio Persona Definition',
    'persona_desc': 'AI will use this info to write like you.',
    'philosophy_label': 'Studio Philosophy',
    'differentiators_label': 'Differentiators',
    'avoid_terms_label': 'Terms to Avoid',
    'save_persona_btn': 'Save Persona',
    'creations_today': 'Creations Today',
    'limit_reached': 'Daily Limit Reached',
    'limit_desc': 'You have reached the creation limit.',
    'what_create': 'What are we creating today?',
    'theme_label': 'Content Theme',
    'format_label': 'Format',
    'objective_label': 'Objective',
    'audience_label': 'Audience',
    'visual_style_label': 'Visual Style',
    'logo_config_label': 'Logo Configuration',
    'generate_btn': 'Generate Content',
    'recent_posts': 'Recently Saved Posts',
    'result_title': 'Generated Result',
    'download_media': 'Download Media',
    'observations_label': 'Observations',
    'refine_btn': 'Regenerate',
    'new_plan': 'Generate New Strategic Plan',
    'duration_label': 'Plan Duration',
    'frequency_label': 'Posts per Week',
    'start_date_label': 'Start Date',
    'generate_calendar_btn': 'Generate Calendar',
    'saved_plans': 'Saved Plans',

    // Financial Agent
    'finance_title': 'Financial Calculator',
    'finance_subtitle': 'Simulate hiring costs and economic viability.',
    'projected_revenue': 'Projected Revenue',
    'compare_models': 'Model Comparison',
    'cost_details': 'Cost Details',
    'ai_analysis': 'Smart Analysis',
    'generate_analysis_btn': 'Generate Analysis',
    'save_simulation_btn': 'Save Analysis',
    'download_pdf': 'Download PDF',

    // Pricing Agent
    'pricing_title': 'Smart Pricing',
    'pricing_subtitle': 'Define your pricing based on real costs.',
    'step_by_step': 'Step by Step',
    'full_view': 'Full View',
    'step': 'Step',
    'studio_info_title': 'Studio Info',
    'fixed_costs_title': 'Monthly Fixed Costs',
    'variable_costs_title': 'Variable Costs & Profit',
    'capacity_title': 'Operational Capacity',
    'market_title': 'Market Analysis (Optional)',
    'pricing_history': 'Pricing History',

    // Settings
    'settings_title': 'Studio Settings',
    'settings_subtitle': 'Manage platform preferences and language.',
    'email_integration': 'Email Integration',
    'email_desc': 'Connect your Gmail to easily send messages.',
    'language_settings': 'Language Preferences',
    'language_desc': 'Choose the display language for your user.',

    // Login
    'welcome_login': 'Welcome',
    'login_subtitle': 'Login to access the platform',
    'email_label': 'Email',
    'password_label': 'Password',
    'enter_button': 'Sign In',
    'no_account': 'No account?',
    'register_link': 'Register Studio',
    'login_error': 'Invalid email or password.',

    // Dashboard
    'hello': 'Hello',
    'dashboard_welcome': 'Welcome to the management dashboard of',
    'step_1_title': 'Records & Organization',
    'step_1_desc': 'The foundation of your studio. Keep data up to date.',
    'step_2_title': 'Planning & Execution',
    'step_2_desc': 'Smart tools to manage daily operations and define the future.',
    'step_3_title': 'Tracking & Quality',
    'step_3_desc': 'Monitor results, satisfaction, and student progress.',
    'card_profile_desc': 'Configure your brand, contacts, and system preferences.',
    'card_team_desc': 'Manage records and access control for your team.',
    'card_students_desc': 'Registration forms, contacts, and app access management.',
    'card_strategy_desc': 'Define vision, mission, and annual action plan with AI consulting.',
    'card_rehab_desc': 'Pathology guide and class generator with clinical triage.',
    'card_content_desc': 'Create posts, captions, and calendars for social media.',
    'card_finance_desc': 'Simulate hiring scenarios and operating costs.',
    'card_pricing_desc': 'Calculate the ideal price for your classes and monthly plans.',
    'card_newsletter_desc': 'Write professional announcements and notices in seconds.',
    'card_evolution_desc': 'Register progress, pain points, and generate performance reports.',
    'card_ratings_desc': 'Monitor daily student feedback on classes.',
    'card_suggestions_desc': 'Analyze feedback and create improvement plans with AI.',
    'access_link': 'Access',

    // Profile
    'profile_basic_info': 'Basic Information',
    'studio_name_label': 'Studio Name',
    'owner_name_label': 'Owner Name',
    'bio_label': 'Studio Biography',
    'ai_write_btn': 'AI Write for me',
    'visual_identity': 'Visual Identity',
    'logo_label': 'Logo',
    'brand_color_label': 'Main Color',
    'services_label': 'Services',
    'specialties_label': 'Specialties',
    'contact_label': 'Contact',
    'address_label': 'Address',
    'phone_label': 'Phone',
    'website_label': 'Website',
    'save_profile_btn': 'Save Profile',

    // Students
    'students_title': 'Studio Students',
    'my_students_title': 'My Students',
    'students_subtitle': 'Manage registration and portal access.',
    'new_student_btn': 'New Student',
    'name_col': 'Name',
    'contact_col': 'Contact',
    'access_col': 'Access',
    'student_name_label': 'Full Name',
    'student_email_label': 'Email (Login)',
    'student_cpf_label': 'ID/SSN',
    'student_obs_label': 'Clinical Observations',
    'save_student_btn': 'Register & Grant Access',
    'update_student_btn': 'Save Changes',
    'no_students_found': 'No students found.',

    // Admin
    'admin_title': 'Global Admin Panel',
    'admin_subtitle': 'Complete management of users and metrics.',
    'admin_tab_dashboard': 'Dashboard',
    'admin_tab_list': 'Full List',
    'admin_tab_owners': 'Owners',
    'admin_tab_instructors': 'Instructors',
    'admin_tab_students': 'Students',
    'admin_tab_suggestions': 'Suggestions',
    'admin_kpi_studios': 'Total Studios',
    'admin_kpi_students': 'Total Students',
    'admin_kpi_content': 'Content Generated',
    'admin_kpi_engagement': 'Engagement',
    'admin_timeline_title': 'Evolution Over Time',
    'admin_dist_users': 'Active User Distribution',
    'admin_vol_prod': 'Production Volume',
    'admin_avg_instructors': 'Avg Instructors',
    'admin_avg_students': 'Avg Students',
    'admin_avg_posts': 'Avg Posts',
    'admin_avg_engagement': 'Avg Engagement',

    // Strategy Agent
    'strategy_agent_title': 'AI Strategic Planner',
    'strategy_agent_desc': 'Transform your goals into a clear and practical action plan.',
    'create_plan': 'Create New Plan',
    'view_history': 'View History',
    'business_identity': 'Business Identity',
    'mission': 'Mission',
    'vision': 'Vision',
    'swot_analysis': 'SWOT Analysis',
    'strengths': 'Strengths',
    'weaknesses': 'Weaknesses',
    'opportunities': 'Opportunities',
    'threats': 'Threats',
    'strategic_objectives': 'Strategic Objectives',
    'action_plan': 'Action Plan',
    'generate_report': 'Generate Report',
    'review': 'Review',

    // Rehab Agent
    'rehab_agent_title': 'Pilates Rehab',
    'clinical_guide': 'Smart Clinical Guide',
    'clinical_guide_desc': 'Select a student and describe the pathology to generate a safe lesson plan.',
    'select_student_required': '1. Select Student (Required)',
    'main_complaint': '2. Main Complaint (e.g., Hernia, Shoulder Pain...)',
    'consult': 'Consult',
    'reference': 'Reference',
    'lesson_plan': 'Lesson Plan',
    'exercise_bank': 'Exercise Bank',
    'indicated': 'Indicated',
    'contraindicated': 'Contraindicated',
    'save_to_bank': 'Save to Bank',
    'create_exercise': 'New Exercise',

    // Newsletter Agent
    'newsletter_title': 'Newsletter Creator',
    'newsletter_subtitle': 'Create professional announcements with AI help.',
    'create_new': 'Create New',
    'target_audience': 'Target Audience',
    'topic_label': 'Topic / Subject',
    'style_label': 'Text Style',
    'generate_newsletter': 'Generate Newsletter',
    'preview': 'Preview',
    'generated_success': 'Generated Successfully',
    'discard': 'Discard',
    'audience_students': 'Students',
    'audience_instructors': 'Instructors',
    'audience_both': 'General',

    // Evolution
    'evolution_title': 'Student Evolution',
    'evolution_subtitle': 'Progress tracking and reports.',
    'new_entry': 'New Entry',
    'reports_analysis': 'Reports & Analysis',
    'individual_record': 'Individual Record',
    'execution': 'Execution',
    'stability': 'Stability',
    'mobility': 'Mobility',
    'strength': 'Strength',
    'coordination': 'Coordination',
    'complaints_care': 'Complaints & Care',
    'pain': 'Pain',
    'limitation': 'Limitation',
    'contraindication': 'Contraindication',
    'save_evaluation': 'Save Evaluation',
    'recent_history': 'Recent History',
    'generate_evolution_report': 'Generate AI Evolution Report',
    'evolution_filters': 'Analysis Filters',

    // Evaluations (Ratings)
    'evaluations_title': 'Class Ratings',
    'evaluations_subtitle': 'Feedback received from students after classes.',
    'evaluations_list': 'Evaluations List',
    'saved_reports': 'Saved Reports',
    'average': 'Average',
    'analyze_ai': 'Analyze with AI',
    'filters': 'Filters',
    'all_instructors': 'All Instructors',
    'all_students': 'All Students',
    'all_period': 'All Period',
    'last_week': 'Last Week',
    'last_month': 'Last Month',
    'quality_report': 'Quality Report',

    // Suggestions
    'suggestions_title': 'Suggestions Management',
    'suggestions_subtitle': 'Transform student feedback into practical action plans.',
    'inbox': 'Inbox',
    'analyze_list': 'Analyze List',
    'generate_action_plan': 'Generate Action Plan',
    'recent_suggestions': 'Recent Suggestions',
    'action_plan_generated': 'Action Plan Generated',
    'trends_report': 'Trends Report',
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Menu & General
    'general_panel': 'Painel Geral',
    'registrations': 'Cadastros',
    'studio_profile': 'Perfil do Studio',
    'team': 'Equipe',
    'students': 'Meus Alunos',
    'settings': 'Configurações',
    'strategy': 'Estratégia',
    'planning_ai': 'Planejamento IA',
    'pilates_rehab': 'Pilates Rehab',
    'content_agent': 'Assistente Conteúdo',
    'finance_calc': 'Calculadora Financeira',
    'smart_pricing': 'Preço Inteligente',
    'newsletter': 'Criador Newsletter',
    'tracking': 'Acompanhamento',
    'student_evolution': 'Evolução do Aluno',
    'class_ratings': 'Avaliações Aulas',
    'suggestions': 'Sugestões Alunos',
    'dark_mode': 'Escuro',
    'light_mode': 'Claro',
    'logout': 'Sair',
    'admin_panel': 'Painel Admin',
    'owner': 'Dono',
    'instructor': 'Instrutor',
    'student': 'Aluno',
    'save_all': 'Salvar Tudo',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'loading': 'Carregando...',
    'search': 'Buscar...',
    'actions': 'Ações',
    'active': 'Ativo',
    'inactive': 'Inativo',
    'new': 'Novo',
    'view_details': 'Ver Detalhes',
    'back': 'Voltar',
    'next': 'Próximo',
    'history': 'Histórico',
    'clear': 'Limpar',
    
    // Content Agent
    'content_title': 'Assistente de Conteúdo',
    'content_subtitle': 'Crie posts, imagens e vídeos alinhados à sua marca.',
    'tab_persona': 'Minha Marca',
    'tab_generator': 'Criar',
    'tab_planner': 'Planejador',
    'persona_title': 'Definição da Persona do Studio',
    'persona_desc': 'A IA usará estas informações para escrever como você.',
    'philosophy_label': 'Filosofia do Studio',
    'differentiators_label': 'Diferenciais',
    'avoid_terms_label': 'Linguagem a Evitar',
    'save_persona_btn': 'Salvar Persona',
    'creations_today': 'Criações Hoje',
    'limit_reached': 'Limite Diário Atingido',
    'limit_desc': 'Você atingiu o limite de criações.',
    'what_create': 'O que vamos criar hoje?',
    'theme_label': 'Tema do Conteúdo',
    'format_label': 'Formato',
    'objective_label': 'Objetivo',
    'audience_label': 'Público',
    'visual_style_label': 'Estilo Visual',
    'logo_config_label': 'Configuração de Logo',
    'generate_btn': 'Gerar Conteúdo',
    'recent_posts': 'Posts Salvos Recentemente',
    'result_title': 'Resultado Gerado',
    'download_media': 'Baixar Mídia',
    'observations_label': 'Observações',
    'refine_btn': 'Regenerar',
    'new_plan': 'Gerar Novo Plano Estratégico',
    'duration_label': 'Duração do Plano',
    'frequency_label': 'Posts por Semana',
    'start_date_label': 'Data de Início',
    'generate_calendar_btn': 'Gerar Calendário',
    'saved_plans': 'Planos Salvos',

    // Financial Agent
    'finance_title': 'Calculadora Financeira',
    'finance_subtitle': 'Simule custos de contratação e viabilidade econômica.',
    'projected_revenue': 'Faturamento Projetado',
    'compare_models': 'Comparativo de Modelos',
    'cost_details': 'Detalhamento dos Custos',
    'ai_analysis': 'Análise Inteligente',
    'generate_analysis_btn': 'Gerar Parecer',
    'save_simulation_btn': 'Salvar Análise',
    'download_pdf': 'Baixar PDF',

    // Pricing Agent
    'pricing_title': 'Preço Certo Inteligente',
    'pricing_subtitle': 'Defina sua precificação com base em custos reais.',
    'step_by_step': 'Passo a Passo',
    'full_view': 'Visão Completa',
    'step': 'Passo',
    'studio_info_title': 'Informações do Studio',
    'fixed_costs_title': 'Custos Fixos Mensais',
    'variable_costs_title': 'Custos Variáveis e Lucro',
    'capacity_title': 'Capacidade Operacional',
    'market_title': 'Análise de Mercado (Opcional)',
    'pricing_history': 'Histórico de Precificação',
    
    // Settings
    'settings_title': 'Configurações do Studio',
    'settings_subtitle': 'Gerencie preferências e idioma da plataforma.',
    'email_integration': 'Integração de Email',
    'email_desc': 'Conecte seu Gmail para facilitar o envio de mensagens.',
    'language_settings': 'Preferências de Idioma',
    'language_desc': 'Escolha o idioma de exibição da plataforma.',

    // Login
    'welcome_login': 'Bem-vindo(a)',
    'login_subtitle': 'Faça login para acessar a plataforma',
    'email_label': 'Email',
    'password_label': 'Senha',
    'enter_button': 'Entrar',
    'no_account': 'Não tem conta?',
    'register_link': 'Cadastrar Studio',
    'login_error': 'Email ou senha incorretos.',

    // Dashboard
    'hello': 'Olá',
    'dashboard_welcome': 'Bem-vindo ao painel de gestão do',
    'step_1_title': 'Cadastros & Organização',
    'step_1_desc': 'A base do seu estúdio. Mantenha os dados sempre atualizados.',
    'step_2_title': 'Planejamento e Execução',
    'step_2_desc': 'Ferramentas inteligentes para gerir o dia a dia e definir o futuro.',
    'step_3_title': 'Acompanhamento & Qualidade',
    'step_3_desc': 'Monitore resultados, satisfação e evolução dos alunos.',
    'card_profile_desc': 'Configure sua marca, contatos e preferências do sistema.',
    'card_team_desc': 'Gerencie cadastros e controle de acesso da sua equipe.',
    'card_students_desc': 'Fichas de cadastro, contatos e gestão de acesso ao app.',
    'card_strategy_desc': 'Defina visão, missão e plano de ação anual com consultoria IA.',
    'card_rehab_desc': 'Guia de patologias e gerador de aulas com triagem clínica.',
    'card_content_desc': 'Crie posts, legendas e calendários para redes sociais.',
    'card_finance_desc': 'Simule cenários de contratação e custos operacionais.',
    'card_pricing_desc': 'Calcule o preço ideal da sua hora-aula e mensalidades.',
    'card_newsletter_desc': 'Escreva comunicados e avisos profissionais em segundos.',
    'card_evolution_desc': 'Registre progresso, dores e gere relatórios de desempenho.',
    'card_ratings_desc': 'Monitore o feedback diário dos alunos sobre as aulas.',
    'card_suggestions_desc': 'Analise feedbacks e crie planos de melhoria com IA.',
    'access_link': 'Acessar',

    // Profile
    'profile_basic_info': 'Informações Básicas',
    'studio_name_label': 'Nome do Studio',
    'owner_name_label': 'Nome do Proprietário(a)',
    'bio_label': 'Biografia do Studio',
    'ai_write_btn': 'IA Escreva para mim',
    'visual_identity': 'Identidade Visual',
    'logo_label': 'Logomarca',
    'brand_color_label': 'Cor Principal',
    'services_label': 'Serviços',
    'specialties_label': 'Especialidades',
    'contact_label': 'Contato',
    'address_label': 'Endereço',
    'phone_label': 'Telefone',
    'website_label': 'Site',
    'save_profile_btn': 'Salvar Perfil',

    // Students
    'students_title': 'Alunos do Studio',
    'my_students_title': 'Meus Alunos',
    'students_subtitle': 'Gerencie o cadastro e acesso ao portal.',
    'new_student_btn': 'Novo Aluno',
    'name_col': 'Nome',
    'contact_col': 'Contato',
    'access_col': 'Acesso',
    'student_name_label': 'Nome Completo',
    'student_email_label': 'Email (Login)',
    'student_cpf_label': 'CPF',
    'student_obs_label': 'Observações Clínicas',
    'save_student_btn': 'Cadastrar e Liberar Acesso',
    'update_student_btn': 'Salvar Alterações',
    'no_students_found': 'Nenhum aluno encontrado.',

    // Admin
    'admin_title': 'Painel Admin Global',
    'admin_subtitle': 'Gestão completa de usuários e métricas.',
    'admin_tab_dashboard': 'Dashboard',
    'admin_tab_list': 'Lista Completa',
    'admin_tab_owners': 'Donos',
    'admin_tab_instructors': 'Instrutores',
    'admin_tab_students': 'Alunos',
    'admin_tab_suggestions': 'Sugestões',
    'admin_kpi_studios': 'Total Studios',
    'admin_kpi_students': 'Total Alunos',
    'admin_kpi_content': 'Conteúdo Gerado',
    'admin_kpi_engagement': 'Engajamento',
    'admin_timeline_title': 'Evolução no Tempo',
    'admin_dist_users': 'Distribuição de Usuários Ativos',
    'admin_vol_prod': 'Volume de Produção',
    'admin_avg_instructors': 'Média Instrutores',
    'admin_avg_students': 'Média Alunos',
    'admin_avg_posts': 'Média Posts',
    'admin_avg_engagement': 'Média Engajamento',

    // Strategy Agent
    'strategy_agent_title': 'Planejador Estratégico AI',
    'strategy_agent_desc': 'Transforme seus objetivos em um plano de ação claro e prático.',
    'create_plan': 'Criar Novo Plano',
    'view_history': 'Ver Histórico',
    'business_identity': 'Identidade do Negócio',
    'mission': 'Missão',
    'vision': 'Visão',
    'swot_analysis': 'Análise SWOT',
    'strengths': 'Forças',
    'weaknesses': 'Fraquezas',
    'opportunities': 'Oportunidades',
    'threats': 'Ameaças',
    'strategic_objectives': 'Objetivos Estratégicos',
    'action_plan': 'Plano de Ação',
    'generate_report': 'Gerar Relatório',
    'review': 'Revisão',
    
    // Rehab Agent
    'rehab_agent_title': 'Pilates Rehab',
    'clinical_guide': 'Guia Clínico Inteligente',
    'clinical_guide_desc': 'Selecione um aluno e descreva a patologia para gerar um plano de aula seguro.',
    'select_student_required': '1. Seleccione o Aluno (Obrigatório)',
    'main_complaint': '2. Queixa Principal (Ex: Hérnia, Dor no Ombro...)',
    'consult': 'Consultar',
    'reference': 'Referência',
    'lesson_plan': 'Plano de Aula',
    'exercise_bank': 'Banco de Exercícios',
    'indicated': 'Indicados',
    'contraindicated': 'Contra-Indicados',
    'save_to_bank': 'Salvar no Banco',
    'create_exercise': 'Novo Exercício',

    // Newsletter Agent
    'newsletter_title': 'Criador de Newsletter',
    'newsletter_subtitle': 'Crie comunicados profissionais com ajuda da IA.',
    'create_new': 'Criar Nova',
    'target_audience': 'Público Alvo',
    'topic_label': 'Tópico / Assunto',
    'style_label': 'Estilo do Texto',
    'generate_newsletter': 'Gerar Newsletter',
    'preview': 'Pré-visualização',
    'generated_success': 'Gerado com Sucesso',
    'discard': 'Descartar',
    'audience_students': 'Alunos',
    'audience_instructors': 'Instrutores',
    'audience_both': 'Geral',

    // Evolution
    'evolution_title': 'Evolução do Aluno',
    'evolution_subtitle': 'Acompanhamento de progresso e relatórios.',
    'new_entry': 'Nova Avaliação',
    'reports_analysis': 'Relatórios & Análise',
    'individual_record': 'Registro Individual',
    'execution': 'Execução',
    'stability': 'Estabilidade',
    'mobility': 'Mobilidade',
    'strength': 'Força',
    'coordination': 'Coordenação',
    'complaints_care': 'Queixas e Cuidados',
    'pain': 'Dor',
    'limitation': 'Limitação',
    'contraindication': 'Contraindicação',
    'save_evaluation': 'Salvar Avaliação',
    'recent_history': 'Histórico Recente',
    'generate_evolution_report': 'Gerar Relatório de Evolução IA',
    'evolution_filters': 'Filtros de Análise',

    // Evaluations (Ratings)
    'evaluations_title': 'Avaliações das Aulas',
    'evaluations_subtitle': 'Feedback recebido dos alunos após as aulas.',
    'evaluations_list': 'Lista de Avaliações',
    'saved_reports': 'Relatórios Salvos',
    'average': 'Média',
    'analyze_ai': 'Analisar com IA',
    'filters': 'Filtros',
    'all_instructors': 'Todos Instrutores',
    'all_students': 'Todos Alunos',
    'all_period': 'Todo o Período',
    'last_week': 'Última Semana',
    'last_month': 'Último Mês',
    'quality_report': 'Relatório de Qualidade',

    // Suggestions
    'suggestions_title': 'Gestão de Sugestões',
    'suggestions_subtitle': 'Transforme feedback dos alunos em planos de ação práticos.',
    'inbox': 'Caixa de Entrada',
    'analyze_list': 'Analisar Lista',
    'generate_action_plan': 'Gerar Plano de Ação',
    'recent_suggestions': 'Sugestões Recentes',
    'action_plan_generated': 'Plano de Ação Gerado',
    'trends_report': 'Relatório de Tendências',
  },
  en: enTranslations,
  es: {
    // Menu & General
    'general_panel': 'Panel General',
    'registrations': 'Registros',
    'studio_profile': 'Perfil del Estudio',
    'team': 'Equipo',
    'students': 'Mis Alumnos',
    'settings': 'Configuraciones',
    'strategy': 'Estratégia',
    'planning_ai': 'Planificación IA',
    'pilates_rehab': 'Pilates Rehab',
    'content_agent': 'Asistente Contenido',
    'finance_calc': 'Calculadora Fin.',
    'smart_pricing': 'Precio Inteligente',
    'newsletter': 'Creador Newsletter',
    'tracking': 'Seguimiento',
    'student_evolution': 'Evolución Alumno',
    'class_ratings': 'Evaluaciones Clases',
    'suggestions': 'Sugerencias',
    'dark_mode': 'Oscuro',
    'light_mode': 'Claro',
    'logout': 'Salir',
    'admin_panel': 'Panel Admin',
    'owner': 'Dueño',
    'instructor': 'Instructor',
    'student': 'Alumno',
    'save_all': 'Guardar Todo',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'loading': 'Cargando...',
    'search': 'Buscar...',
    'actions': 'Acciones',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'new': 'Nuevo',
    'view_details': 'Ver Detalles',
    'back': 'Volver',
    'next': 'Siguiente',
    'history': 'Historial',
    'clear': 'Limpiar',

    // Content Agent
    'content_title': 'Asistente de Contenido',
    'content_subtitle': 'Crea publicaciones, imágenes y videos alineados con tu marca.',
    'tab_persona': 'Mi Marca',
    'tab_generator': 'Crear',
    'tab_planner': 'Planificador',
    'persona_title': 'Definição de Persona del Estudio',
    'persona_desc': 'La IA usará esta información para escribir como tú.',
    'philosophy_label': 'Filosofía del Estudio',
    'differentiators_label': 'Diferenciales',
    'avoid_terms_label': 'Lenguaje a Evitar',
    'save_persona_btn': 'Guardar Persona',
    'creations_today': 'Creaciones Hoy',
    'limit_reached': 'Límite Diario Alcanzado',
    'limit_desc': 'Has alcanzado el límite de creaciones.',
    'what_create': '¿Qué vamos a crear hoy?',
    'theme_label': 'Tema del Contenido',
    'format_label': 'Formato',
    'objective_label': 'Objetivo',
    'audience_label': 'Público',
    'visual_style_label': 'Estilo Visual',
    'logo_config_label': 'Configuración de Logotipo',
    'generate_btn': 'Generar Contenido',
    'recent_posts': 'Publicaciones Recientes',
    'result_title': 'Resultado Generado',
    'download_media': 'Descargar Medios',
    'observations_label': 'Observaciones',
    'refine_btn': 'Regenerar',
    'new_plan': 'Generar Nuevo Plan Estratégico',
    'duration_label': 'Duración del Plan',
    'frequency_label': 'Publicaciones por Semana',
    'start_date_label': 'Fecha de Inicio',
    'generate_calendar_btn': 'Generar Calendario',
    'saved_plans': 'Planes Guardados',

    // Financial Agent
    'finance_title': 'Calculadora Financiera',
    'finance_subtitle': 'Simule costos de contratación y viabilidade económica.',
    'projected_revenue': 'Ingresos Proyectados',
    'compare_models': 'Comparativo de Modelos',
    'cost_details': 'Detalle de Costos',
    'ai_analysis': 'Análisis Inteligente',
    'generate_analysis_btn': 'Generar Opinión',
    'save_simulation_btn': 'Guardar Análisis',
    'download_pdf': 'Descargar PDF',

    // Pricing Agent
    'pricing_title': 'Precio Inteligente',
    'pricing_subtitle': 'Defina su precio en base a costos reales.',
    'step_by_step': 'Paso a Paso',
    'full_view': 'Vista Completa',
    'step': 'Paso',
    'studio_info_title': 'Información del Estudio',
    'fixed_costs_title': 'Costos Fijos Mensuales',
    'variable_costs_title': 'Costos Variables y Lucro',
    'capacity_title': 'Capacidad Operacional',
    'market_title': 'Análisis de Mercado (Opcional)',
    'pricing_history': 'Historial de Precios',

    // Settings
    'settings_title': 'Configuraciones del Estudio',
    'settings_subtitle': 'Administre preferencias e idioma de la plataforma.',
    'email_integration': 'Integración de Email',
    'email_desc': 'Conecte su Gmail para enviar mensajes fácilmente.',
    'language_settings': 'Preferencias de Idioma',
    'language_desc': 'Elija el idioma de visualización para su usuario.',

    // Login
    'welcome_login': 'Bienvenido(a)',
    'login_subtitle': 'Inicie sesión para acceder',
    'email_label': 'Correo',
    'password_label': 'Contraseña',
    'enter_button': 'Entrar',
    'no_account': '¿No tienes cuenta?',
    'register_link': 'Registrar Estudio',
    'login_error': 'Correo o contraseña incorrectos.',

    // Dashboard
    'hello': 'Hola',
    'dashboard_welcome': 'Bienvenido al panel de gestión de',
    'step_1_title': 'Registros y Organización',
    'step_1_desc': 'La base de su estudio. Mantenga los datos actualizados.',
    'step_2_title': 'Planificación y Ejecución',
    'step_2_desc': 'Herramientas inteligentes para gestionar el día a día.',
    'step_3_title': 'Seguimiento y Calidad',
    'step_3_desc': 'Monitoree resultados, satisfacción y evolución.',
    'card_profile_desc': 'Configure su marca, contactos y preferencias.',
    'card_team_desc': 'Gestione registros y control de acceso de su equipo.',
    'card_students_desc': 'Fichas de registro, contactos y gestión de acceso.',
    'card_strategy_desc': 'Defina visión, misión y plan de acción con IA.',
    'card_rehab_desc': 'Guía de patologías y generador de clases.',
    'card_content_desc': 'Cree publicaciones, leyendas y calendarios.',
    'card_finance_desc': 'Simule escenarios de contratación y costos.',
    'card_pricing_desc': 'Calcule el precio ideal de sus clases.',
    'card_newsletter_desc': 'Escriba comunicados profesionales en segundos.',
    'card_evolution_desc': 'Registre progreso, dolores y genere informes.',
    'card_ratings_desc': 'Monitoree el feedback diario de los alumnos.',
    'card_suggestions_desc': 'Analice feedbacks y cree planes de mejora.',
    'access_link': 'Acceder',

    // Profile
    'profile_basic_info': 'Información Básica',
    'studio_name_label': 'Nombre del Estudio',
    'owner_name_label': 'Nombre del Propietario',
    'bio_label': 'Biografía del Estudio',
    'ai_write_btn': 'IA Escribe para mí',
    'visual_identity': 'Identidad Visual',
    'logo_label': 'Logotipo',
    'brand_color_label': 'Color Principal',
    'services_label': 'Servicios',
    'specialties_label': 'Especialidades',
    'contact_label': 'Contacto',
    'address_label': 'Dirección',
    'phone_label': 'Teléfono',
    'website_label': 'Sitio Web',
    'save_profile_btn': 'Guardar Perfil',

    // Students
    'students_title': 'Alumnos del Estudio',
    'my_students_title': 'Mis Alumnos',
    'students_subtitle': 'Gestione el registro y acceso al portal.',
    'new_student_btn': 'Nuevo Alumno',
    'name_col': 'Nombre',
    'contact_col': 'Contacto',
    'access_col': 'Acceso',
    'student_name_label': 'Nombre Completo',
    'student_email_label': 'Correo (Login)',
    'student_cpf_label': 'DNI/CPF',
    'student_obs_label': 'Observaciones Clínicas',
    'save_student_btn': 'Registrar y Dar Acceso',
    'update_student_btn': 'Guardar Cambios',
    'no_students_found': 'No se encontraron alumnos.',

    // Admin
    'admin_title': 'Panel Admin Global',
    'admin_subtitle': 'Gestión completa de usuarios y métricas.',
    'admin_tab_dashboard': 'Panel',
    'admin_tab_list': 'Lista Completa',
    'admin_tab_owners': 'Dueños',
    'admin_tab_instructors': 'Instructors',
    'admin_tab_students': 'Alumnos',
    'admin_tab_suggestions': 'Sugerencias',
    'admin_kpi_studios': 'Total Estudios',
    'admin_kpi_students': 'Total Alumnos',
    'admin_kpi_content': 'Contenido Generado',
    'admin_kpi_engagement': 'Participación',
    'admin_timeline_title': 'Evolución en el Tiempo',
    'admin_dist_users': 'Distribución de Usuarios Activos',
    'admin_vol_prod': 'Volumen de Producción',
    'admin_avg_instructors': 'Prom. Instructores',
    'admin_avg_students': 'Prom. Alumnos',
    'admin_avg_posts': 'Prom. Posts',
    'admin_avg_engagement': 'Prom. Participación',

    // Strategy Agent
    'strategy_agent_title': 'Planificador Estratégico IA',
    'strategy_agent_desc': 'Transforme sus objetivos en un plan de acción claro y práctico.',
    'create_plan': 'Crear Nuevo Plan',
    'view_history': 'Ver Historial',
    'business_identity': 'Identidad del Negocio',
    'mission': 'Misión',
    'vision': 'Visión',
    'swot_analysis': 'Análisis FODA',
    'strengths': 'Fortalezas',
    'weaknesses': 'Debilidades',
    'opportunities': 'Oportunidades',
    'threats': 'Amenazas',
    'strategic_objectives': 'Objetivos Estratégicos',
    'action_plan': 'Plan de Acción',
    'generate_report': 'Generar Informe',
    'review': 'Revisión',

    // Rehab Agent
    'rehab_agent_title': 'Pilates Rehab',
    'clinical_guide': 'Guía Clínica Inteligente',
    'clinical_guide_desc': 'Seleccione un alumno y describa la patología para generar un plan de clase seguro.',
    'select_student_required': '1. Seleccione al Alumno (Obligatorio)',
    'main_complaint': '2. Queja Principal (Ej: Hernia, Dolor de Hombro...)',
    'consult': 'Consultar',
    'reference': 'Referencia',
    'lesson_plan': 'Plan de Clase',
    'exercise_bank': 'Banco de Ejercicios',
    'indicated': 'Indicados',
    'contraindicated': 'Contraindicados',
    'save_to_bank': 'Guardar en Banco',
    'create_exercise': 'Nuevo Ejercicio',

    // Newsletter Agent
    'newsletter_title': 'Creador de Newsletter',
    'newsletter_subtitle': 'Crea comunicados profesionales con ayuda de IA.',
    'create_new': 'Crear Nueva',
    'target_audience': 'Público Objetivo',
    'topic_label': 'Tema / Asunto',
    'style_label': 'Estilo de Texto',
    'generate_newsletter': 'Generar Newsletter',
    'preview': 'Vista Previa',
    'generated_success': 'Generado con Éxito',
    'discard': 'Descartar',
    'audience_students': 'Alumnos',
    'audience_instructors': 'Instructores',
    'audience_both': 'General',

    // Evolution
    'evolution_title': 'Evolución del Alumno',
    'evolution_subtitle': 'Seguimiento de progreso e informes.',
    'new_entry': 'Nueva Evaluación',
    'reports_analysis': 'Informes y Análisis',
    'individual_record': 'Registro Individual',
    'execution': 'Ejecución',
    'stability': 'Estabilidad',
    'mobility': 'Movilidad',
    'strength': 'Fuerza',
    'coordination': 'Coordinación',
    'complaints_care': 'Quejas y Cuidados',
    'pain': 'Dolor',
    'limitation': 'Limitación',
    'contraindication': 'Contraindicación',
    'save_evaluation': 'Guardar Evaluación',
    'recent_history': 'Historial Reciente',
    'generate_evolution_report': 'Generar Informe de Evolución IA',
    'evolution_filters': 'Filtros de Análisis',

    // Evaluations (Ratings)
    'evaluations_title': 'Evaluaciones de Clases',
    'evaluations_subtitle': 'Comentarios recibidos de los alumnos después de las clases.',
    'evaluations_list': 'Lista de Evaluaciones',
    'saved_reports': 'Informes Guardados',
    'average': 'Promedio',
    'analyze_ai': 'Analizar con IA',
    'filters': 'Filtros',
    'all_instructors': 'Todos los Instructores',
    'all_students': 'Todos los Alumnos',
    'all_period': 'Todo el Período',
    'last_week': 'Última Semana',
    'last_month': 'Último Mes',
    'quality_report': 'Informe de Calidad',

    // Suggestions
    'suggestions_title': 'Gestión de Sugerencias',
    'suggestions_subtitle': 'Transforma los comentarios de los alumnos en planes de acción.',
    'inbox': 'Bandeja de Entrada',
    'analyze_list': 'Analizar Lista',
    'generate_action_plan': 'Generar Plan de Acción',
    'recent_suggestions': 'Sugerencias Recientes',
    'action_plan_generated': 'Plan de Acción Generado',
    'trends_report': 'Informe de Tendencias',
  },
  // --- FALLBACK LANGUAGES (Clone English) ---
  fr: enTranslations,
  de: enTranslations,
  it: enTranslations,
  zh: enTranslations,
  ja: enTranslations,
  ru: enTranslations,
  ko: enTranslations,
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('app_language') as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};